version: '3.9'

services:
  jobs_db:
    image: postgres:15-alpine
    container_name: job_tracker_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${PORTS}
    volumes:
      - pgdata:/var/lib/postgresql/data
